"""
report.py – Generate remediation-focused Markdown reports from finding data.

Reports are intentionally oriented toward helping developers fix issues,
not toward exploiting them.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Sequence


# ---------------------------------------------------------------------------
# Severity ordering for sorting
# ---------------------------------------------------------------------------

_SEVERITY_ORDER = {
    "critical": 0,
    "high": 1,
    "medium": 2,
    "low": 3,
    "info": 4,
}


def _severity_key(finding: dict) -> int:
    return _SEVERITY_ORDER.get(finding.get("severity", "info").lower(), 99)


# ---------------------------------------------------------------------------
# Report rendering
# ---------------------------------------------------------------------------

def render_report(
    scan: dict,
    findings: Sequence[dict],
) -> str:
    """
    Render a Markdown vulnerability report for a single scan.

    Parameters
    ----------
    scan:
        Scan record dict (keys: ``url``, ``scanned_at``, ``status_code``,
        ``error``).
    findings:
        Sequence of finding dicts (keys: ``finding_type``, ``description``,
        ``severity``, ``url``).

    Returns
    -------
    str
        Markdown-formatted report text.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    target_url = scan.get("url", "unknown")
    scanned_at = scan.get("scanned_at", "unknown")
    status_code = scan.get("status_code") or "N/A"
    error = scan.get("error")

    sorted_findings = sorted(findings, key=_severity_key)

    lines: list[str] = []

    # Header
    lines += [
        "# Vulnerability Assessment Report",
        "",
        "> **CONFIDENTIAL** – For authorized assessment use only.  "
        "Do not distribute without permission.",
        "",
        f"**Generated:** {now}  ",
        f"**Target:** `{target_url}`  ",
        f"**Scan timestamp:** {scanned_at}  ",
        f"**HTTP Status:** {status_code}  ",
    ]

    if error:
        lines += [
            "",
            f"⚠️ **Scan error:** {error}",
        ]

    # Summary table
    counts: dict[str, int] = {}
    for f in findings:
        sev = f.get("severity", "info").lower()
        counts[sev] = counts.get(sev, 0) + 1

    lines += [
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
    ]
    for sev in ("critical", "high", "medium", "low", "info"):
        if sev in counts:
            lines.append(f"| {sev.capitalize()} | {counts[sev]} |")

    if not findings:
        lines += [
            "",
            "_No findings recorded for this scan._",
        ]

    # Findings detail
    if sorted_findings:
        lines += [
            "",
            "---",
            "",
            "## Findings",
            "",
        ]
        for idx, finding in enumerate(sorted_findings, start=1):
            ftype = finding.get("finding_type", "unknown")
            sev = finding.get("severity", "info").capitalize()
            desc = finding.get("description", "")
            furl = finding.get("url", "")

            lines += [
                f"### {idx}. [{sev}] {ftype}",
                "",
                f"**Description:** {desc}",
                "",
            ]
            if furl:
                lines.append(f"**URL:** `{furl}`")
                lines.append("")

            lines += _remediation_hint(ftype)
            lines.append("")

    # Footer
    lines += [
        "---",
        "",
        "## Disclaimer",
        "",
        "This report was generated by an **authorized, local-only** assessment "
        "tool.  All findings relate exclusively to systems for which explicit "
        "permission was granted.  No automated exploitation was performed.",
    ]

    return "\n".join(lines)


def _remediation_hint(finding_type: str) -> list[str]:
    """Return generic remediation guidance lines for a given finding type."""
    hints: dict[str, list[str]] = {
        "form": [
            "**Remediation:** Validate and sanitize all form inputs server-side.  "
            "Use parameterized queries to prevent injection.  "
            "Apply CSRF tokens to state-changing forms.",
        ],
        "link": [
            "**Remediation:** Review all outbound links.  "
            "Ensure sensitive endpoints are access-controlled and "
            "not inadvertently exposed.",
        ],
        "header": [
            "**Remediation:** Add missing security headers "
            "(e.g. Content-Security-Policy, X-Content-Type-Options, "
            "Strict-Transport-Security) to harden the HTTP response.",
        ],
        "open_redirect": [
            "**Remediation:** Validate redirect targets against an allowlist of "
            "approved domains.  Never redirect to user-supplied arbitrary URLs.",
        ],
    }
    return hints.get(
        finding_type.lower(),
        [
            "**Remediation:** Investigate the finding and apply the principle of "
            "least privilege.  Consult OWASP guidelines for this vulnerability class.",
        ],
    )


# ---------------------------------------------------------------------------
# File I/O helpers
# ---------------------------------------------------------------------------

def save_report(report_text: str, reports_dir: str, scan_id: int) -> str:
    """
    Write *report_text* to a Markdown file and return the file path.

    Parameters
    ----------
    report_text:
        The rendered Markdown content.
    reports_dir:
        Directory where report files are stored.
    scan_id:
        Used as part of the filename.

    Returns
    -------
    str
        Absolute path to the saved report file.
    """
    Path(reports_dir).mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    filename = f"report_scan{scan_id}_{timestamp}.md"
    path = Path(reports_dir) / filename
    path.write_text(report_text, encoding="utf-8")
    return str(path)
